name: Secret scan (TruffleHog)

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute scan range
        id: range
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
          else
            BASE="${{ github.event.before }}"
            HEAD="${{ github.sha }}"
          fi
          echo "base=$BASE" >> $GITHUB_OUTPUT
          echo "head=$HEAD" >> $GITHUB_OUTPUT

      - name: TruffleHog - scan changed commits (verified-only)
        uses: trufflesecurity/trufflehog@v3.90.8
        with:
          base: ${{ steps.range.outputs.base }}
          head: ${{ steps.range.outputs.head }}
          path: ${{ github.workspace }}
          extra_args: --results=verified,unknown
